main = "../endpoint/build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[vars]
PUBLIC_KEY = "{\"kty\":\"EC\",\"use\":\"sig\",\"crv\":\"P-256\",\"kid\":\"0d2dbad0-81f5-4625-94a8-91e839581ac8\",\"x\":\"F4hIC9DufzIBAolcQsfOpsBEQd6Vgw5T2eci0GzuQM0\",\"y\":\"nkGBEGRI-QZ8AVztb20W2pzulUx_-jWbxiP1cgc89PY\",\"alg\":\"ES256\"}"
BUCKET = "mytiki-publish"
BUCKET_REGION = "us-east-2"

# The necessary secrets are:
# - BUCKET_KEY_ID
# - BUCKET_KEY_SECRET

[build]
command = "cd ../endpoint && cargo install -q worker-build && worker-build --release"
