[package]
name = "ingest-generate"
version = "0.1.3"
edition = "2021"

[dependencies]
mustache = "0.9.0"
config = "0.13.3"
serde = { version = "1.0", features = ["derive"] }
ingest-lib = { path = "../lib" }
