[[schema]]
clazz   = "ShopifyOrder"
in_avro = "shopify_order/shopify_order.avsc"
in_rust = "shopify_order/shopify_order.rs"
in_json = "shopify_order/shopify_order.json"
out     = "shopify_order"

[[schema]]
clazz   = "MicroblinkReceipt"
in_avro = "microblink_receipt/microblink_receipt.avsc"
in_rust = "microblink_receipt/microblink_receipt.rs"
in_json = "microblink_receipt/microblink_receipt.json"
out     = "microblink_receipt"
