name: Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cargo-junit
        run: |
          cargo install cargo-junit

      - name: Run Generate
        run: |
          cd generate && cargo run

      - name: Run Tests
        run: |
          mkdir reports
          (cd endpoint/shopify_order && cargo junit --name "../../reports/shopify_order.xml")
          (cd endpoint/microblink_receipt && cargo junit --name "../../reports/microblink_receipt.xml")

      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: reports/*.xml
